/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddItemForm: typeof import('./src/components/AddItemForm.vue')['default']
    BudgetSummary: typeof import('./src/components/BudgetSummary.vue')['default']
    CompletedItemsSummary: typeof import('./src/components/CompletedItemsSummary.vue')['default']
    GroceryListItem: typeof import('./src/components/GroceryListItem.vue')['default']
    GroceryLists: typeof import('./src/components/GroceryLists.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InvitationDropdown: typeof import('./src/components/InvitationDropdown.vue')['default']
    ItemsList: typeof import('./src/components/ItemsList.vue')['default']
    ItemSuggestions: typeof import('./src/components/ItemSuggestions.vue')['default']
    ListFilters: typeof import('./src/components/ListFilters.vue')['default']
    ListHeader: typeof import('./src/components/ListHeader.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingMode: typeof import('./src/components/ShoppingMode.vue')['default']
    ShoppingModeItem: typeof import('./src/components/ShoppingModeItem.vue')['default']
    ShoppingModeToggle: typeof import('./src/components/ShoppingModeToggle.vue')['default']
    UserManagement: typeof import('./src/components/UserManagement.vue')['default']
  }
}
